### ISSUE TITLE
Separate into Intro and Advanced Workshops?

### ISSUE THREAD

**Issue by paraskakis** [OAI/Talks-and-Workshops#1]
Do you think we should renumber the folders as they are being presented in the conf schedule?

Intro:

1. What’s OpenAPI 3.0
2. OpenAPI and Server Objects
3. Paths and Path Parameters
4. GET Operation and Responses
5. Query and Header Parameters
6. POST, PATCH, and PUT
7. Documentation with markdown

Advanced:

1. Schema Objects
2. External References
3. Form Data
4. Links and Callbacks
5. Security Schemes
6. XmlExample

In the latter, Schema Objects should come after Documentation, a minor reorder needed IMO

ref: https://apistrat18.sched.com/event/GAWE/ and https://apistrat18.sched.com/event/GAWK/

**Comment by webron** [comment]
Should be fixed.
